# Generated by Django 5.2 on 2025-06-10 10:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.IntegerField(default=1, editable=False)),
                ('client_id', models.IntegerField(default=1, editable=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('guest', 'Guest')], default='member', max_length=10)),
                ('user_type', models.CharField(choices=[('internal', 'Internal'), ('guest', 'Guest')], default='internal', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Channel Participant',
                'verbose_name_plural': 'Channel Participants',
            },
        ),
        migrations.CreateModel(
            name='ChatChannel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.IntegerField(default=1, editable=False)),
                ('client_id', models.IntegerField(default=1, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_type', models.CharField(choices=[('direct', 'Direct Message'), ('group', 'Group'), ('contextual_object', 'Contextual Object')], default='group', max_length=20)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('host_application_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('context_object_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('context_object_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='chat_channels', through='chat.ChannelParticipant', through_fields=('channel', 'user'), to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Channel',
                'verbose_name_plural': 'Chat Channels',
            },
        ),
        migrations.AddField(
            model_name='channelparticipant',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='chat.chatchannel'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.IntegerField(default=1, editable=False)),
                ('client_id', models.IntegerField(default=1, editable=False)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatchannel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='chatchannel',
            constraint=models.UniqueConstraint(fields=('host_application_id', 'context_object_type', 'context_object_id'), name='unique_contextual_chat'),
        ),
        migrations.AlterUniqueTogether(
            name='channelparticipant',
            unique_together={('user', 'channel')},
        ),
    ]
